#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

mkdir -v /srv/makerpms/src

echo 'makerpms ALL=NOPASSWD: /usr/bin/yum' > /etc/sudoers.d/10_makerpms
chmod 440 /etc/sudoers.d/10_makerpms

mkdir -v /srv/makerpms/.ssh
chmod -v 700 /srv/makerpms/.ssh
cat - > /srv/makerpms/.ssh/config <<EOF
UserKnownHostsFile=/dev/null
StrictHostKeyChecking=no
EOF
touch /srv/makerpms/.ssh/id_rsa
chmod -v 600 /srv/makerpms/.ssh/config /srv/makerpms/.ssh/id_rsa

chown -R -c makerpms:makerpms ~makerpms
