#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

yum -y --setopt=tsflags=nodocs install http://packages.nethserver.org/nethserver/nethserver-release-7.rpm epel-release
yum -y --setopt=tsflags=nodocs install sudo rpmdevtools yum-utils git nethserver-devtools perl sed
yum clean all
rm -rf /var/cache/yum/*
useradd -m -d /srv/makerpms -r makerpms
mkdir /srv/makerpms/src /srv/makerpms/.ssh
chmod 700 /srv/makerpms/.ssh
cat - > /srv/makerpms/.ssh/config <<EOF
UserKnownHostsFile=/dev/null
StrictHostKeyChecking=no
IdentityFile=~/upload/identity
EOF
chmod 600 /srv/makerpms/.ssh/config
chown makerpms.makerpms \
    /srv/makerpms/src \
    /srv/makerpms/.ssh \
    /srv/makerpms/.ssh/config \
    ;

echo 'makerpms ALL=NOPASSWD: /usr/bin/yum' > /etc/sudoers.d/10_makerpms
chmod 440 /etc/sudoers.d/10_makerpms
chown -v root.root /usr/local/bin/make{rpms,srpm} /usr/local/sbin/buildimage
chmod -v 755 /usr/local/bin/make{rpms,srpm} /usr/local/sbin/buildimage
