#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

if (( EUID != 0 )); then
    exec "$@"
fi

src_owner_uid=$(stat -c %u /srv/makerpms/src)
src_owner_gid=$(stat -c %g /srv/makerpms/src)

if [[ $(id -u makerpms) != ${src_owner_uid} || $(id -g makerpms) != ${src_owner_gid} ]]; then
    echo "[INFO] Changing makerpms uid/gid to ${src_owner_uid}/${src_owner_gid}"
    groupmod -g ${src_owner_gid} makerpms
    usermod -u ${src_owner_uid} -g ${src_owner_gid} makerpms
    chown -f -R makerpms:makerpms ~makerpms
fi

exec runuser -u makerpms -- "$@"
