#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

topdir=$(rpm --eval '%_topdir')

#
# Variables from environment:
#
# NSVER
# TRAVIS_TAG
# TRAVIS_PULL_REQUEST_BRANCH
# TRAVIS_BRANCH
# TRAVIS_COMMIT
# TRAVIS_PULL_REQUEST

IFS=- read desc_tag desc_commitn desc_commith <<<$(git describe --tags --match "[0-9]*" --abbrev=7 HEAD 2>/dev/null)

export DIST

if [[ -n "${TRAVIS_TAG}" ]]; then
    # tagged release
    DIST=.ns${NSVER}
elif [[ -z "${TRAVIS_PULL_REQUEST_BRANCH}" && "${TRAVIS_BRANCH}" == "master" ]]; then
    # testing
    DIST=.${desc_commitn}.g${TRAVIS_COMMIT:0:7}.ns${NSVER}
else
    # autobuild
    DIST=.${desc_commitn}.pr${TRAVIS_PULL_REQUEST}.g${TRAVIS_COMMIT:0:7}.ns${NSVER}
fi

exec makerpms "$@"
