#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Sanitize arguments with new call style
if [[ $1 == "-s" ]]; then
    echo "[WARNING] the -s flag is no more required. Use '$0 filename.spec [arg]...' instead." 1>&2
    shift
fi

topdir=$(rpm --eval '%_topdir')

# Run makesrpm first, if src RPM is not available:
if [[ ${topdir}/SRPMS/*.src.rpm == "${topdir}/SRPMS/*.src.rpm" ]]; then
    makesrpm "$@"
    if [[ $? != 0 ]]; then
        exit 1
    fi
fi

# Skip the .spec file argument
shift

echo '[INFO] Installing build deps...'
PATH=/usr/bin sudo yum install -y --setopt=tsflags=nodocs ${YUM_ARGS} $(rpm -qp --requires ${topdir}/SRPMS/*.src.rpm)

echo '[INFO] Rebuild ' ${topdir}/SRPMS/*.src.rpm
exec rpmbuild -D "dist ${DIST:-.ns7}" --rebuild ${topdir}/SRPMS/*.src.rpm "$@"
