#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Variables from environment:
#
# DEST_ID
# UPLOAD_DEST
# NSVER
# VERSIONS_PACK
# STAGES_PACK
# TRAVIS_TAG
# TRAVIS_PULL_REQUEST
# TRAVIS_PULL_REQUEST_BRANCH
# TRAVIS_BRANCH
# TRAVIS_REPO_SLUG
# SECRET
# SECRET_URL
# NETHBOT_GITHUB_TOKEN

SECRET=${SECRET:-${AUTOBUILD_SECRET}}
SECRET_URL=${SECRET_URL:-${AUTOBUILD_SECRET_URL}}

UPLOAD_DEST=${UPLOAD_DEST:-travisbot@packages.nethserver.org:nscom}

declare -A "versions=(${VERSIONS_PACK})"
declare -A "stages=(${STAGES_PACK})"

IFS=- read desc_tag desc_commitn desc_commith <<<$(git describe --tags --match "[0-9]*" --abbrev=7 HEAD 2>/dev/null)

if [[ -z "${desc_commitn}" && -z "${desc_commith}" ]]; then
    repo_name=${stages[${DEST_ID}-updates]}
elif [[ -z "${TRAVIS_PULL_REQUEST_BRANCH}" ]]; then
    repo_name=${stages[${DEST_ID}-testing]}
else
    repo_name=${stages[${DEST_ID}-autobuild]}
fi

# Clean up the private key and shutdown agent
trap '> /srv/makerpms/.ssh/id_rsa; kill $SSH_AGENT_PID' EXIT

curl -s "${SECRET_URL}" > /srv/makerpms/.ssh/id_rsa

eval $(ssh-agent)

expect << EOF
  spawn ssh-add /srv/makerpms/.ssh/id_rsa
  expect "Enter passphrase"
  send "${SECRET}\r"
  expect eof
EOF

unset SECRET SECRET_URL

find $(rpm --eval '%_topdir') -type f -name '*.rpm' | xargs -- rpm -qp --queryformat="\[UPLOAD_SHA1\] %{NVRA} %{SOURCEPACKAGE} %{SHA1HEADER}\n"

uploadrpms "$@" ${UPLOAD_DEST}/${versions[$NSVER]}/${repo_name}

if [[ $? != 0 ]]; then
    echo "[ERROR] sftp upload error" 1>&2
    exit 1
fi
