#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# usage:
#      uploadrpms [RPMDIR] SFTOPTS
#
# .rpm files are searched under RPMDIR recursively and uploaded with sftp
# according to SFTPOPTS
#

set -e

if [[ -n "$1" && -d "$1" ]]; then
    cd "$1";
    shift;
else 
    cd $(rpm --eval '%_topdir')
fi

username=$(whoami)
for arg in "$@"; do
    if [[ $arg =~ \@ ]]; then
        username=${arg%%\@*}
        break
    fi
done

tmpcmd=$(mktemp)

trap "rm -f $tmpcmd" EXIT

(
    spool=$(mktemp -u "${username}.XXXXXX");
    echo "mkdir $spool";
    echo "cd $spool";
    for F in $(find . -name '*.rpm'); do
        echo "put -p $F";
    done;
    echo "cd ..";
    echo "rename $spool commit-$spool"
) >>$tmpcmd

sftp -b "${tmpcmd}" "$@"
